#ifndef GENCKT_DEFINE_DEFINE_H
#define GENCKT_DEFINE_DEFINE_H

/*
 * @filename : Define.h
 * @author   : Hao Limin
 * @date:    : 2020.08.09
 * @desp     : Basic defines
 */

#include <string>

#ifndef LINE_INFO
#define LINE_INFO "\n[" << __FILE__ << " : line " << __LINE__ << " : " << __FUNCTION__ << "()] - "
#endif

#ifndef TRACE_LINE
#define TRACE_LINE "\n[" << __FILE__ << " : line " << __LINE__ << " : " << __FUNCTION__ << "()]"
#endif 

#ifndef UNUSED
#define UNUSED(x) (void*)(x)
#endif

/* Disallow copy and assign functions that generated by compiler. */
 #define DISALLOW_COPY_AND_ASSIGN(TypeName) \
    TypeName(const TypeName &);             \
    TypeName &operator=(const TypeName &)

#define OKAY  0
#define ERROR 1

#define NOT !
#define AND &&

#define EXIT exit(1)

/* For ClockTree circuit */
const static int MAX_H_LENGTH = 3;

enum AnalysisType { OP = 0, DC, AC, TRAN };

/* For DC */
const std::string V_DC = "10";
const std::string V_START = "0";
const std::string V_STOP = "10";
const std::string V_INCR = "1";

/* For AC */
const std::string STEP_TYPE = "DEC";
const std::string NUM_STEPS = "10";
const std::string FSTART = "1";
const std::string FSTOP  = "1G";
const std::string V_AC_MAG = "1";
const std::string V_AC_MAG1 = "1";
const std::string V_AC_MAG2 = "2";

// #define RVAL RandomDouble(0.1, 10)
#define RVAL 100
// #define CVAL RandomDouble(1e-14, 1e-12)
#define CVAL 1e-12
#define LVAL RandomDouble(1e-4, 1e-2)
// #define LVAL 1e-3

const static int L_GAP = 5;
const static int COUPLED_NUM = 10;

#endif // GENCKT_DEFINE_DEFINE_H
